openapi: '3.0.2'
info:
  title: Something Object
  version: '1.0'
servers:
  - url: https://api.server.test/v1

paths:
  /Something/{Id}:
    get:
      summary: get someting by id
      operationId: getById
      tags: 
        - "something"
      "parameters": 
        - name: "Id"
          in: "path"
          required: true
          description: "ID of something to return"
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: "OK"
          content: 
            application/json:
              schema: 
                $ref: "#/components/schemas/Something"
        '400':
          description: "Invalid Id"
        '404':
          description: "Something Not Found"
        '405':
          description: "valdiation exception"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Something: 
      type: object
      required: 
        - Id
      properties:
        id: 
          type: integer
          format: int64
          example: 1
        textValue:
          type: string
          example: "Text Value"
        dateValue: 
          type: string
          format: date-time
          example: "2021/01/01 04:00:00"
    Error:
      type: object
      required:
        - code
        - message 
      properties:
        code: 
          type: "integer"
          format: int32
        message:
          type: string
